Repository benruehl/adonis-ui, pull requests merged in 2020-10, with the labels that each got.

#122 Fix github pages vulnerability
  docs/Gemfile
  docs/Gemfile.lock
Labels: dependencies

#123 Add contributing.md
  CONTRIBUTING.md
Labels: documentation

#124 Fix watermark alignment
  src/AdonisUI.ClassicTheme/DefaultStyles/ComboBox.xaml
  src/AdonisUI.ClassicTheme/DefaultStyles/DatePicker.xaml
  src/AdonisUI.ClassicTheme/DefaultStyles/TextBox.xaml
Labels: bug

#125 Fix content alignment for bullet decorators
  src/AdonisUI.ClassicTheme/DefaultStyles/CheckBox.xaml
  src/AdonisUI.ClassicTheme/DefaultStyles/RadioButton.xaml
Labels: bug

#128 Address `Allow hiding of the window title in the title bar #127`
  docs/docs/guides/window.md
  src/AdonisUI/Controls/AdonisWindow.cs
  src/AdonisUI/Controls/AdonisWindow.xaml
  src/AdonisUI/Converters/AllVisibilitiesToVisibilityConverter.cs
Labels: enhancement

#134 Fix window position on double click minimize
  src/AdonisUI/Controls/AdonisWindow.cs
Labels: bug
